# Generated by Django 5.2.6 on 2025-10-19 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todotask',
            old_name='name',
            new_name='task_name',
        ),
    ]
