# Generated by Django 5.2.6 on 2025-10-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_rename_name_todotask_task_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todotask',
            name='id',
        ),
        migrations.AddField(
            model_name='todotask',
            name='todo_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
