# Generated by Django 5.2.6 on 2025-10-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_remove_todotask_id_todotask_todo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todotask',
            name='todo_id',
        ),
        migrations.AddField(
            model_name='todotask',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
