# Generated by Django 5.2.6 on 2025-10-24 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student',
            new_name='todo_user',
        ),
    ]
