# Generated by Django 5.2.6 on 2025-10-24 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_rename_student_todo_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='todo_user',
        ),
    ]
